---
title: "Examen de Genómica"
date: today
date-format: "DD MMMM, YYYY"
author: 
  Mathias
institute: "Facultad de Ciencias, Universidad de la República"
abstract: |
    Proyecto de genomica
abstractspacing: double
appendix: false
fontfamily: libertine
monofont: inconsolata
monofontoptions: scaled=.95
fontsize: 12pt
geometry: 
  - top=2cm
  - bottom=2cm
  - left=2cm
  - right=2cm
urlcolor: blue
highlight-style: arrow
csl: /home/mathias/Descargas/apa.csl
bibliography: /home/mathias/Descargas/Kinetoplastidos.bib
reference-section-title: "Referencias"
keywords: [genómica, NGS, pseudogenes, Kinetoplastida]
lang: es

format: 
    pdf:
      toc: true
      toc-depth: 2
      number-sections: true
      colorlinks: true
      link-citations: true
      linkcolor: black
      urlcolor: blue
      citecolor: black
      keep-tex: true
      fig-cap-location: top


---

# Introducción

Los kinetoplástidos (clase *Kinetoplastea*) conforman un grupo diverso de protistas flagelados dentro del filo *Euglenozoa*, caracterizados por la presencia de un ADN mitocondrial de una organización compleja, conocido como cinetoplasto [@lukesKinetoplastDNANetwork2002]. Este linaje incluye especies de vida libre como *Bodo saltans*, así como patógenos obligados de vertebrados e invertebrados, tales como *Trypanosoma cruzi*, *T. brucei* y *Leishmania* spp., responsables de enfermedades como el mal de Chagas, la tripanosomiasis africana y la leishmaniasis [@cosentinoPhasedGenomeAssembly2021; @el-sayedGenomeSequenceTrypanosoma2005; @steverdingHistoryLeishmaniasis2017].

Una observación recurrente en los genomas de kinetoplástidos es la presencia de proteínas de longitud grandes, que superan los 3000 aminoácidos. Aunque la mayoría de las proteínas eucariotas tienen entre 100 y 500 aminoácidos [@neversProteinLengthDistribution2023], las proteínas gigantes (PGs, ≥ 3000 aa) han sido poco estudiadas y plantean un desafío evolutivo, dado el alto costo energético que implica su sintesis, plegamientos y otros procesos [@amaralNeglectedGiantsUncovering2024]. El tamaño de estas PGs sugiere una conservación bajo presion selectiva, lo que la convierte en elementos interesantes para explorar aspectos estructurales, funcionales y evolutivos.

A pesar de estas caracteristicas, existen ejemplos bien caracterizados de PGs en otros organismos. En vertebrados, la titina destaca como una de las proteínas más grandes conocidas, siendo fundamental para la arquitectura de los músculos esqueléticos y cardíacos, y representa la tercera proteína más abundante del músculo, después de la miosina y la actina [@wangTitinMajorMyofibrillar1979]. En bacterias, por su parte, las PGs suelen participar en funciones como la adhesión celular o la síntesis de metabolitos secundarios complejos [@amaralNeglectedGiantsUncovering2024].

En kinetoplástidos, sin embargo, el origen, función y evolución de estas PGs permanecen en gran medida poco estudiadas. La comparación entre *Bodo saltans*, que representa un linaje basal de vida libre [@jacksonKinetoplastidPhylogenomicsReveals2016], y los parásitos derivados, proporciona un marco evolutivo ideal para investigar los cambios en el repertorio de PGs asociados a la transición hacia el parasitismo. Esta transición implica tanto ganancia como pérdida de funciones. Las PGs conservadas en *Bodo* pero ausentes en los parásitos podrían reflejar una pérdida secundaria de proteínas necesarias para funciones propias de la vida libre, como la respuesta al ambiente o la competencia por recursos. Por otro lado, las PGs que aparecen exclusivamente en los parásitos podrían estar vinculadas a adaptaciones parasitarias. Por ejemplo, proteínas de superficie implicadas en la evasión inmune o en la interacción prolongada con el hospedador [@jacksonKinetoplastidPhylogenomicsReveals2016]. Finalmente, las PGs conservadas entre ambos estilos de vida probablemente representen funciones celulares esenciales y ancestrales para el linaje *kinetoplástido*, como la organización del citoesqueleto, el mantenimiento mitocondrial o la regulación postranscripcional.

Un estudio sistemático de las PGs permitira abordar la comparación entre especies de vida libre, como *Bodo saltans*, y especies parásitas ofreciendo un marco evolutivo para investigar cómo se ha transformado el repertorio de PGs durante la transición al parasitismo. Este enfoque puede revelar tanto pérdidas como innovaciones funcionales, permitiendo identificar proteínas conservadas con funciones esenciales, así como casos de pérdida secundaria o pseudogenización vinculados a la reducción de capacidades asociadas a un estilo de vida libre.

# Objetivos

## Objetivo general:
En este trabajo nos proponemos caracterizar la diversidad, conservación y evolución de PGs en los kinetoplástidos.

## Objetivos específicos:
1. Identificar y filtrar proteínas de más de 3000 aminoácidos en un conjunto representativo de genomas de kinetoplástidos.

2. Comparar el repertorio de HPs entre especies de vida libre *Bodo saltans* y especies parásitas (*Trypanosoma*, *Leishmania*, etc.).

3. Evaluar la conservación de dominios funcionales y arquitectura mediante anotación funcional.

4. Inferir posibles funciones biológicas basado en el análisis de homología.

5. Proponer una hipótesis sobre el rol de las PGs en la transición hacia el parasitismo.

# Materiales y Métodos

## Herramientas y entorno de trabajo
Todos los análisis de filtrado, búsqueda, anotación y visualización fueron realizados en un entorno Linux utilizando R 4.5.1 y Bash scripting. Se utilizaron las siguientes herramientas y librerías:

Seqkit (v1.31) para manipulación de secuencias FASTA y GFF.
Dplyr (v1.1.4), tidyverse (v2.0.0) y ggplot2 (v3.5.2) para el procesamiento y visualización de datos.
InterProScan (v5.75-106.0) para anotación funcional y de dominios.
BLAST+ (v2.13.0), específicamente PSI-BLAST, para detección de homologías entre proteínas.
HMMER (v3.3.2), particularmente hmmbuild y hmmsearch, para detección sensible de homologías distantes.
MAFFT (v7.513) y TrimAl (v7.515) para alineamientos múltiples y el recorte del alineamiento.
iTOl (v7) para visualización y IQ-TREE (v2.4.0) análisis filogenético.
QUAST (v5.3.0) para evaluación de ensamblajes genómicos.
BUSCO (v5.4.4) para evaluación de la completitud genómica basada en genes ortólogos universales.

## Datasets y filtrado inicial
Se utilizará genomas anotados de especies representativas de *Kinetoplastea*, descargados de TriTrypDB y NCBI. En total se analizaran genomas de especies de vida libre *Bodo saltans* y especies parásitas de los géneros *Trypanosoma* y *Leishmania* entre otros.
Para garantizar la calidad y confiabilidad del análisis, se realizará una evaluación del estado de los ensamblajes genómicos utilizando QUAST, obteniendo métricas como el número de contigs, el N50 y el L50. Complementariamente, se evaluará la completitud genómica mediante BUSCO con el conjunto de genes. Se excluirán del análisis aquellos ensamblajes con números altos de contigs, con un N50 muy chicos, un L50 muy alto y con prcentajes bajos de genes BUSCO completos, a fin de evitar la inclusión de genomas fragmentados que pudieran afectar la detección y anotación correcta de PGs.
Las secuencias codificantes (CDSs) van a ser extraídas a partir de los archivos GFF/GFF3 provistos por las respectivas bases de datos, y filtradas para obtener aquellas cuya traducción produce PGs. La extracción inicial se limitará a secuencias codificantes anotadas.

## Análisis de dominios
La anotación funcional de las PGs se realizará con InterProScan, utilizando el conjunto completo de bases de datos integradas (Pfam, SMART, Panther, TIGRFAM, ProSite, entre otras) y un umbral de e-value de 0.001. Las salidas se generaran en formato TSV y fueron procesadas para asociar, en cada PG, los dominios conservados, repeticiones y motivos funcionales, junto con su posición relativa dentro de la proteína.

Además de los dominios funcionales, se utilizara las predicciones integradas de regiones transmembrana (TMHMM) y péptidos señal (SignalP, Phobius), también provistas por InterProScan, para inferir la topología de las proteínas.

## Comparación evolutiva y detección de ortólogos
Para evaluar la conservación evolutiva de las PGs, se realizará una búsqueda entre especies utilizando PSI-BLAST (tres iteraciones, e-valor 1e-5, cobertura mínima del 30%). A partir de las relaciones de homología identificadas, se seleccionaron conjuntos de PGs conservadas para construir alineamientos múltiples con MAFFT. Estos alineamientos fueron utilizados para generar perfiles HMM mediante hmmbuild. Posteriormente, se aplicara hmmsearch para detectar homologías remotas entre las PGs. Este enfoque combinado permitira identificar tanto homólogos cercanos como relaciones evolutivas más distantes, proporcionando un escenario más completo de la diversidad y conservación de estas proteínas en kinetoplástidos.

## Visualización y agrupamiento
Se visualizarán la distribución de longitudes de las PGs, el número de dominios por proteína y la abundancia de dominios por especie mediante gráficos de densidad, diagramas de violín y gráficos de barras acumulativos. Además, se utilizarán árboles filogenéticos de especies para mapear la presencia o ausencia de familias de PGs a lo largo de la evolución de los kinetoplástidos, así como la distribucion cromosómica.

# Resultados Esperados
Se espera obtener un repertorio completo y caracterizado de las PGs codificadas en genomas de kinetoplástidos, incluyendo especies de vida libre como es *Bodo saltans* y diversos parásitos como *Trypanosoma (T. cruzi, T. brucei)* y especies del género *Leishmania* entre otros. A partir de este análisis, se prevé la identificación de PGs conservadas en todo el clado, lo que sugeriría funciones ancestrales esenciales, mantenidas independientemente del estilo de vida.

Como paso previo, se aplicarán criterios de calidad basados en métricas de ensamblado y anotacion genómica, con el fin de seleccionar únicamente genomas de alta calidad. Este filtrado permitirá trabajar con conjuntos confiables de secuencias codificantes, minimizando errores derivados de ensamblados fragmentados o anotaciones incompletas, y asegurando la calidad de las PGs.

Asimismo, se espera identificar PGs específicas de los linajes parásitos, potencialmente implicadas en procesos adaptativos como la evasión de la respuesta inmune, la interacción con el hospedador o la organización de estructuras celulares especializadas vinculadas al parasitismo.

Por otra lado, se anticipa la detección de un subconjunto de PGs exclusivas de *Bodo saltans*, lo que podría reflejar que estas proteínas están asociadas a funciones propias del estilo de vida libre. Su ausencia en especies parásitas sugiere una pérdida secundaria asociada a la simplificación funcional que caracteriza a la transición al parasitismo.

Tambien se espera el reconocimiento de posibles eventos de pseudogenización en PGs, particularmente aquellos que aparecen como genes completos en *Bodo saltans* pero se encuentran truncadas, fragmentadas o interrumpidas en parásitos. Este patrón podría interpretarse como una pérdida funcional, vinculada a la relajación de la presión selectiva sobre funciones no esenciales en contextos parasitarios.

La clasificación funcional de las PGs se realizará mediante anotación de dominios (InterProScan) y agrupamiento por ortología (PSI-BLAST, HMMER), lo que permitirá inferir posibles roles estructurales, enzimáticos o reguladores.

A partir del análisis de presencia o ausencia, conservación de dominios y eventos de pseudogenización, se buscará reconstruir el repertorio ancestral de PGs y su historia evolutiva a lo largo de la filogenenia de los kinetoplástidos.

A partir de estos análisis, se podra contextualizar cómo se ha modificado el repertorio de PGs a lo largo de la evolución de los kinetoplástidos, considerando tanto su conservación como su pérdida total o parcial (pseudogenización). Finalmente, se evaluará si las PGs comparten arquitecturas estructurales diferenciadas según el estilo de vida, lo que permitiría identificar posibles correlaciones funcionales entre dominios conservados y contextos ecológicos específicos.